# Site settings
title: App Permissions
email: none
description: > # this means to ignore newlines until "baseurl:"
  App Permissions 
baseurl: "~/home/jason/AppPermissions/app/"
url: "swtchrly08.github.io/AppPermissions" 
twitter_username: none
github_username:  swtchrly08

# Build settings
markdown: kramdown
